### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by Dupel01** [DeFiSolMaster/Solana-Sniper-Bot-Opensource#2]
rpc simulateTransaction error
    at Logger.makeError (C:\Users\Dupel\Downloads\Solana-Sniper-Bot-Opensource-main\node_modules\@raydium-io\raydium-sdk\lib\cjs\common\logger.js:176:23)
    at Logger.throwError (C:\Users\Dupel\Downloads\Solana-Sniper-Bot-Opensource-main\node_modules\@raydium-io\raydium-sdk\lib\cjs\common\logger.js:185:20)
    at C:\Users\Dupel\Downloads\Solana-Sniper-Bot-Opensource-main\node_modules\@raydium-io\raydium-sdk\lib\cjs\common\web3.js:187:31
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Dupel\Downloads\Solana-Sniper-Bot-Opensource-main\node_modules\@raydium-io\raydium-sdk\lib\cjs\common\web3.js:6:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'failed to simulate for instructions',
  code: 'RPC_ERROR'
}
C:\Users\Dupel\Downloads\Solana-Sniper-Bot-Opensource-main\build\main.js:203
                    console.log(`\n\tAmount out: ${amountOut.toFixed()},\n\tMin Amount out: ${minAmountOut.toFixed()}`);
                                                             ^

TypeError: Cannot read properties of undefined (reading 'toFixed')
    at C:\Users\Dupel\Downloads\Solana-Sniper-Bot-Opensource-main\build\main.js:203:62
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Dupel\Downloads\Solana-Sniper-Bot-Opensource-main\build\main.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by d4op** [comment]
can you proof this bot is working ?
